### ISSUE TITLE
License rendered as package docs

### ISSUE THREAD

**Issue by artyom** [steakknife/bloomfilter#11]
See https://godoc.org/github.com/steakknife/bloomfilter — package docs list multiple license headers from .go files since these comment headers immediately precede package declaration like here:

https://github.com/steakknife/bloomfilter/blob/b93b7b6483ff7a38a9d22474b3061090afb6b0aa/bloomfilter.go#L9-L11

There should be an empty newline before `package ...` to avoid rendering them as package documentation.

**Comment by steakknife** [comment]
Submit a PR
